# Generated by Django 4.0 on 2022-03-03 20:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='tableno',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tno', models.IntegerField()),
                ('tstatus', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='tbooking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fname', models.CharField(max_length=20)),
                ('lname', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=50)),
                ('phone', models.IntegerField(default=0)),
                ('capacity', models.IntegerField()),
                ('date', models.DateField()),
                ('time', models.TimeField()),
                ('rstatus', models.CharField(max_length=20, null=True)),
                ('Tableno', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='myapp.tableno')),
            ],
        ),
    ]
