# Generated by Django 4.0 on 2022-03-04 08:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tbooking',
            name='Tableno',
        ),
    ]
