# Generated by Django 4.0 on 2022-03-04 08:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_remove_tbooking_tableno'),
    ]

    operations = [
        migrations.AddField(
            model_name='tbooking',
            name='tno',
            field=models.IntegerField(null=True),
        ),
    ]
