# Generated by Django 4.0 on 2022-03-08 19:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_tbooking_tno'),
    ]

    operations = [
        migrations.AddField(
            model_name='tbooking',
            name='pic',
            field=models.FileField(blank=True, null=True, upload_to='profile/'),
        ),
    ]
