# Generated by Django 4.0 on 2022-03-08 22:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_tbooking_pic'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tbooking',
            name='pic',
            field=models.FileField(default='abc.jpg', upload_to='profile/'),
        ),
    ]
