# Generated by Django 4.0 on 2022-03-11 08:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0006_category_menu'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='cid',
            field=models.CharField(default=0, max_length=20),
        ),
    ]
