# Generated by Django 4.0 on 2022-03-13 10:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0009_menu_availablity_menu_item_desc_menu_pic'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menu',
            name='item_desc',
            field=models.TextField(default='enjoy your food', max_length=50),
        ),
    ]
