# Generated by Django 4.0 on 2022-03-13 11:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0010_alter_menu_item_desc'),
    ]

    operations = [
        migrations.RenameField(
            model_name='menu',
            old_name='pic',
            new_name='mpic',
        ),
    ]
