# Generated by Django 4.0 on 2022-03-13 14:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0011_rename_pic_menu_mpic'),
    ]

    operations = [
        migrations.RenameField(
            model_name='menu',
            old_name='mpic',
            new_name='pic',
        ),
    ]
