# Generated by Django 4.0 on 2022-03-16 15:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0014_customercart'),
    ]

    operations = [
        migrations.DeleteModel(
            name='customercart',
        ),
    ]
