# Generated by Django 4.0 on 2022-03-16 18:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0016_customercart'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customercart',
            name='order_id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
