# Generated by Django 4.0 on 2022-03-16 19:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0017_alter_customercart_order_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='cart',
            fields=[
                ('order_id', models.AutoField(primary_key=True, serialize=False)),
                ('item_id', models.IntegerField()),
                ('user_id', models.IntegerField()),
            ],
        ),
    ]
