# Generated by Django 4.0 on 2022-03-18 06:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0018_cart'),
    ]

    operations = [
        migrations.AddField(
            model_name='customercart',
            name='item_quantity',
            field=models.IntegerField(default=1),
        ),
    ]
