# Generated by Django 4.0 on 2022-03-18 07:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0019_customercart_item_quantity'),
    ]

    operations = [
        migrations.AddField(
            model_name='customercart',
            name='totalPrice',
            field=models.IntegerField(default=0),
        ),
    ]
