# Generated by Django 4.0 on 2022-03-20 20:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0020_customercart_totalprice'),
    ]

    operations = [
        migrations.CreateModel(
            name='login',
            fields=[
                ('trans_id', models.AutoField(primary_key=True, serialize=False)),
                ('cust_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.tbooking')),
            ],
        ),
    ]
