# Generated by Django 4.0 on 2022-03-20 20:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0021_login'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='login',
            new_name='clogin',
        ),
    ]
