# Generated by Django 4.0 on 2022-03-20 21:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0022_rename_login_clogin'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clogin',
            name='cust_id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='myapp.tbooking'),
        ),
    ]
