# Generated by Django 4.0 on 2022-03-21 08:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0023_alter_clogin_cust_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clogin',
            name='cust_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.tbooking'),
        ),
    ]
