# Generated by Django 4.0 on 2022-03-21 09:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0024_alter_clogin_cust_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='customercart',
            name='ctrans_id',
            field=models.ForeignKey(default=7, on_delete=django.db.models.deletion.CASCADE, to='myapp.clogin'),
        ),
    ]
