# Generated by Django 4.0 on 2022-03-21 19:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0026_order'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='payment_status',
            field=models.CharField(default='unpaid', max_length=20),
        ),
        migrations.AlterField(
            model_name='order',
            name='process_status',
            field=models.CharField(default='accept', max_length=20),
        ),
    ]
