# Generated by Django 4.0 on 2022-03-22 04:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0028_rename_order_yourorder'),
    ]

    operations = [
        migrations.AddField(
            model_name='yourorder',
            name='cust_number',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='yourorder',
            name='item_quantity',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='yourorder',
            name='order_item',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='yourorder',
            name='totalPrice',
            field=models.IntegerField(default=0),
        ),
    ]
