# Generated by Django 4.0 on 2022-03-22 06:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0029_yourorder_cust_number_yourorder_item_quantity_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='yourorder',
            name='order_id',
            field=models.IntegerField(default=1),
        ),
    ]
