# Generated by Django 4.0 on 2022-03-22 22:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0030_alter_yourorder_order_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='yourorder',
            name='order_item',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='myapp.menu'),
        ),
    ]
