# Generated by Django 4.0 on 2022-03-22 22:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0031_alter_yourorder_order_item'),
    ]

    operations = [
        migrations.CreateModel(
            name='myorder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_id', models.IntegerField(default=1)),
                ('cust_number', models.IntegerField(default=1)),
                ('item_quantity', models.IntegerField(default=1)),
                ('totalPrice', models.IntegerField(default=0)),
                ('payment_status', models.CharField(default='unpaid', max_length=20)),
                ('process_status', models.CharField(default='accept', max_length=20)),
                ('cust_details', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='myapp.tbooking')),
                ('order_item', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='myapp.menu')),
            ],
        ),
    ]
