# Generated by Django 4.0 on 2022-03-25 10:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0033_check'),
    ]

    operations = [
        migrations.CreateModel(
            name='transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('trans_id', models.IntegerField()),
                ('total_price', models.IntegerField()),
                ('paid_status', models.CharField(max_length=20)),
            ],
        ),
    ]
