# Generated by Django 4.0 on 2022-03-25 20:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0034_transaction'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='paid_status',
            field=models.CharField(default='unpaid', max_length=20),
        ),
    ]
